[build]
  publish = "."
  functions = "netlify/functions"

# Specificăm bundlerul Node pentru funcțiile Netlify
[functions]
  node_bundler = "esbuild"

# Antet CORS aplicat doar pe funcțiile serverless
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json; charset=utf-8"
